-- 002_gen_tokens.sql (aligned for prod + idempotent)
-- Caps global concurrent generations across all app processes.

-- === 0) Configurable pool size (psql variable). Default 8. Override with: -v token_count=12
\set token_count 8

-- === 1) Ensure table exists
CREATE TABLE IF NOT EXISTS gen_tokens (
                                          id        integer PRIMARY KEY,
                                          in_use    boolean NOT NULL DEFAULT false,
                                          taken_by  text,
                                          taken_at  timestamptz
);

-- === 2) Upgrade id -> identity (safe if already identity)
DO $$
BEGIN
ALTER TABLE gen_tokens
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
EXCEPTION
  WHEN duplicate_object THEN
    -- already identity; ignore
    NULL;
WHEN others THEN
    -- If column already has a DEFAULT or identity, ignore
    NULL;
END $$;

-- === 3) Ensure sensible defaults
ALTER TABLE gen_tokens
    ALTER COLUMN in_use SET DEFAULT false;

-- === 4) Seed EXACTLY :token_count tokens (idempotent)
DO $$
DECLARE
target_count integer := :token_count;
  cur_count    integer;
  need         integer;
BEGIN
SELECT COUNT(*) INTO cur_count FROM gen_tokens;

IF cur_count < target_count THEN
    need := target_count - cur_count;
INSERT INTO gen_tokens(in_use)
SELECT false FROM generate_series(1, need);
ELSIF cur_count > target_count THEN
    -- Remove extras (highest ids first)
DELETE FROM gen_tokens
WHERE id IN (
    SELECT id FROM gen_tokens ORDER BY id DESC LIMIT (cur_count - target_count)
    );
END IF;
END $$;

-- === 5) Handy query: tokens stuck > 2 minutes
-- SELECT * FROM gen_tokens WHERE in_use = true AND taken_at < now() - interval '2 minutes';
