-- 002_gen_tokens.sql  (psql-safe, idempotent, sequence-correct)

-- --- 0) Desired token pool size (override with: -v token_count=12)
\set token_count 8

-- --- 1) Ensure table exists (neutral if already there)
CREATE TABLE IF NOT EXISTS gen_tokens (
                                          id        integer PRIMARY KEY,
                                          in_use    boolean NOT NULL DEFAULT false,
                                          taken_by  text,
                                          taken_at  timestamptz
);

-- --- 2) Check identity status and set a boolean flag for psql \if
-- psql \if doesn't do string comparisons; turn condition into on/off.
WITH q AS (
    SELECT is_identity
    FROM information_schema.columns
    WHERE table_schema = current_schema()
      AND table_name   = 'gen_tokens'
      AND column_name  = 'id'
    LIMIT 1
    )
SELECT CASE WHEN (SELECT is_identity FROM q) = 'NO' THEN 'on' ELSE 'off' END AS need_identity;
\gset

\if :need_identity
ALTER TABLE gen_tokens
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
\endif

-- --- 3) Ensure default for in_use
ALTER TABLE gen_tokens
    ALTER COLUMN in_use SET DEFAULT false;

-- --- 4) Advance identity sequence to MAX(id) to avoid duplicates
-- (works for both SERIAL/IDENTITY)
SELECT pg_get_serial_sequence('gen_tokens','id') AS gen_tokens_seq;
\gset

-- If a sequence exists, set it to MAX(id) so nextval = MAX(id)+1.
-- Use 'on'/'off' gate because \if expects boolean-ish text.
SELECT CASE WHEN (SELECT pg_get_serial_sequence('gen_tokens','id')) IS NULL
                THEN 'off' ELSE 'on' END AS have_seq;
\gset

\if :have_seq
SELECT setval(
               pg_get_serial_sequence('gen_tokens','id'),
               COALESCE((SELECT MAX(id) FROM gen_tokens), 0),
               true  -- is_called: so nextval returns max(id)+1
       );
\endif

-- --- 5) Seed to EXACTLY :token_count rows (pure SQL, idempotent)

-- 5a) Insert missing rows (lets identity assign new ids)
WITH c AS (SELECT COUNT(*) AS cur FROM gen_tokens)
INSERT INTO gen_tokens(in_use)
SELECT false
FROM c, generate_series(1, GREATEST(0, :token_count - c.cur)) g;

-- 5b) Delete extras (highest ids first)
WITH c AS (SELECT COUNT(*) AS cur FROM gen_tokens)
DELETE FROM gen_tokens
WHERE id IN (
    SELECT id
    FROM gen_tokens
    ORDER BY id DESC
    LIMIT GREATEST(0, (SELECT c.cur FROM c) - :token_count)
    );

-- --- 6) Optional quick check
-- SELECT COUNT(*) AS tokens, MIN(id) AS min_id, MAX(id) AS max_id FROM gen_tokens;
