-- 002_gen_tokens.sql  (psql-safe, no DO blocks; idempotent)

-- --- 0) Desired token pool size (can override at CLI: -v token_count=12)
\set token_count 8

-- --- 1) Ensure table exists (neutral if already there)
CREATE TABLE IF NOT EXISTS gen_tokens (
                                          id        integer PRIMARY KEY,
                                          in_use    boolean NOT NULL DEFAULT false,
                                          taken_by  text,
                                          taken_at  timestamptz
);

-- --- 2) If id is not an identity column yet, upgrade it (idempotent)
-- Query current identity status into a psql variable
SELECT is_identity AS gen_tokens_is_identity
FROM information_schema.columns
WHERE table_schema = current_schema()
  AND table_name   = 'gen_tokens'
  AND column_name  = 'id'
    LIMIT 1;
\gset

\if :gen_tokens_is_identity = 'NO'
ALTER TABLE gen_tokens
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
\endif

-- --- 3) Ensure sensible defaults
ALTER TABLE gen_tokens
    ALTER COLUMN in_use SET DEFAULT false;

-- --- 4) Seed to EXACTLY :token_count rows (no DO; pure SQL)

-- 4a) Insert missing rows (uses identity/default if present)
WITH c AS (SELECT COUNT(*) AS cur FROM gen_tokens)
INSERT INTO gen_tokens(in_use)
SELECT false
FROM c, generate_series(1, GREATEST(0, :token_count - c.cur)) g;

-- 4b) Delete extras (highest ids first)
WITH c AS (SELECT COUNT(*) AS cur FROM gen_tokens)
DELETE FROM gen_tokens
WHERE id IN (
    SELECT id
    FROM gen_tokens
    ORDER BY id DESC
    LIMIT GREATEST(0, (SELECT c.cur FROM c) - :token_count)
    );

-- --- 5) Optional: quick check
-- SELECT COUNT(*) AS tokens, MIN(id) AS min_id, MAX(id) AS max_id FROM gen_tokens;
